app:
  TOKEN_EXPIRATION: 10
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8195
spring:
  application:
    name: question-service
  redis:
    host: localhost
    password: password
    port: 6379
  datasource:
    password: anchal29
    url: jdbc:mysql://localhost:3306/oes?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     