app:
  TOKEN_EXPIRATION: 10
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8192
service:
  upload-service:
    serviceId: upload-service
spring:
  application:
    name: student-service
  datasource:
    password: anchal29
    url: jdbc:mysql://localhost:3306/sms?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  redis:
    port: 6379
    host: localhost
    password: password
tpd:
  messages-per-request: 10
  topic-name: Welcome_Email1
